twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        cartService: "@App\\Cart\\CartService"
    paths:
        'assets/styles': styles

when@test:
    twig:
        strict_variables: true
